apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: papiknomic/udagram-api-feed:v1
        imagePullPolicy: Always          
        resources:
          limits:
            memory: "4096Mi"
            cpu: "2"
          requests:
            memory: "1024Mi"
            cpu: "300m" 
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: aws-secret
          - secretRef:
              name: env-secret
      volumes:
      - configMap:
          name: env-configmap
        name: feed-volume
        
